import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Authprovider from "./context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import Header from "@/components/ui/custome/Header";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Authprovider>
      <body
      className="flex flex-col h-screen w-screen"
      >
        <Header/>
        {children}
        <Toaster />
      </body>
      </Authprovider>
    </html>
  );
}
